project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - talks/*/index.qmd
  resources:
    - .nojekyll

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    toc: false

website:
  title: "SB5 Climate SDM Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Talks
