project:
  type: website
  output-dir: docs

execute:
  freeze: auto

format:
  revealjs:
    theme:
      - default
      - shared/theme/sb5.scss
    widescreen: true
    slide-number: true
    hash: true
    transition: none
    background-transition: none
    controls: true
    progress: true
    center: false
    margin: 0.04
    code-overflow: wrap

website:
  title: "SB5 Climate SDM Presentations"
